# exec(open("../cnn/cnn_nohumidityds_categoricalcrossentropy_adam.py").read())
# exec(open("../cnn/cnn_nohumidityds_categoricalcrossentropy_adam_normalized.py").read())
# exec(open("../cnn/cnn_nohumidityds_categoricalcrossentropy_adam_smaller_normalization.py").read())
# exec(open("../cnn/cnn_nohumiditydsreduced_categoricalcrossentropy_adam.py").read())
# exec(open("../cnn/cnn_fullds_categoricalcrossentropy_adam.py").read())
#
# exec(open("../decisiontree/decisiontree_fullds.py").read())
# exec(open("../decisiontree/decisiontree_nohumidityds.py").read())
# exec(open("../decisiontree/decisiontree_nohumiditydsreduced.py").read())
#
# exec(open("../lstm/lstm_nohumidityds_categoricalcrossentropy_adam.py").read())
# exec(open("../lstm/lstm_fullds_categoricalcrossentropy_adam.py").read())
# exec(open("../lstm/lstm_fullds_categoricalcrossentropy_adam_bidirectional.py").read())
# exec(open("../lstm/lstm_nohumidityds_categoricalcrossentropy_adam_bidirectional.py").read())
# exec(open("../lstm/lstm_nohumiditydsreduced_categoricalcrossentropy_adam.py").read())
# exec(open("../lstm/lstm_nohumiditydsreduced_categoricalcrossentropy_adam_bidirectional.py").read())
# exec(open("../lstm/lstm_nohumidityds_categoricalcrossentropy_adam_normalized.py").read())
# exec(open("../lstm/lstm_nohumidityds_categoricalcrossentropy_adam_smaller_normalization.py").read())
# exec(open("../lstm/lstm_nohumidityds_categoricalcrossentropy_adam_three_layer.py").read())
#
# exec(open("../mlp/mlp_fullds_categoricalcrossentropy_adam.py").read())
# exec(open("../mlp/mlp_fullds_meansquarederror_adam.py").read())
# exec(open("../mlp/mlp_nohumidityds_categoricalcrossentropy_adam.py").read())
# exec(open("../mlp/mlp_nohumidityds_categoricalcrossentropy_adam_smaller_normalization.py").read())
# exec(open("../mlp/mlp_nohumidityds_categoricalcrossentropy_adam_normalized.py").read())
# exec(open("../mlp/mlp_nohumidityds_meansquarederror_adam.py").read())
# exec(open("../mlp/mlp_nohumiditydsreduced_categoricalcrossentropy_adam.py").read())
# exec(open("../mlp/mlp_nohumiditydsreduced_meansquarederror_adam.py").read())
#
# exec(open("../resnet/resnet_fullds_categoricalcrossentropy_adam.py").read())
# exec(open("../resnet/resnet_nohumidityds_categoricalcrossentropy_adam.py").read())
# exec(open("../resnet/resnet_nohumiditydsreduced_categoricalcrossentropy_adam.py").read())
# exec(open("../resnet/resnet_nohumidityds_categoricalcrossentropy_adam_normalized.py").read())
# exec(open("../resnet/resnet_nohumidityds_categoricalcrossentropy_adam_smaller_normalization.py").read())

exec(open("../cnn+lstm/cnn+lstm_nohumidityds_categoricalcrossentropy_adam.py").read())
exec(open("../cnn+lstm/cnn+lstm_nohumidityds_categoricalcrossentropy_adam_normalized.py").read())
exec(open("../cnn+lstm/cnn+lstm_nohumidityds_categoricalcrossentropy_adam_smaller_normalization.py").read())
exec(open("../cnn+lstm/cnn+lstm_nohumiditydsreduced_categoricalcrossentropy_adam.py").read())
exec(open("../cnn+lstm/cnn+lstm_fullds_categoricalcrossentropy_adam.py").read())


# exec(open("../other/mlp_nohumidityds_categoricalcrossentropy_adam_greater_normalization.py").read())
# exec(open("../other/mlp_nohumidityds_categoricalcrossentropy_adam_greatest_normalization.py").read())
# exec(open("../other/cnn+lstm_nohumidityds_categoricalcrossentropy_adam_greater_normalization.py").read())
# exec(open("../other/cnn+lstm_nohumidityds_categoricalcrossentropy_adam_greatest_normalization.py").read())
# exec(open("../other/resnet_nohumidityds_categoricalcrossentropy_adam_greater_normalization.py").read())
# exec(open("../other/resnet_nohumidityds_categoricalcrossentropy_adam_greatest_normalization.py").read())
# exec(open("../other/lstm_nohumidityds_categoricalcrossentropy_adam_greater_normalization.py").read())
# exec(open("../other/lstm_nohumidityds_categoricalcrossentropy_adam_greatest_normalization.py").read())
# exec(open("../other/cnn_nohumidityds_categoricalcrossentropy_adam_greater_normalization.py").read())
# exec(open("../other/cnn_nohumidityds_categoricalcrossentropy_adam_greatest_normalization.py").read())